# odczytaj to - demonstruje odczytywaniendanych z pliku tekstowego

print("Otwarcie i zamknięcie pliku.")
dok_tekst = open("odczytaj_to.txt", "r")
dok_tekst.close()
print()
print("Odczytywanie znaków z pliku.")
dok_tekst = open("odczytaj_to.txt", "r")
print(dok_tekst.read(1))
print(dok_tekst.read(7))
dok_tekst.close()
print()
print("Odczytywanie całego pliku za jednym razem.")
dok_tekst = open("odczytaj_to.txt", "r")
print(dok_tekst.read())
dok_tekst.close()
print()
print("Odczytywanie znaków wiersza.")
dok_tekst = open("odczytaj_to.txt", "r")
print(dok_tekst.readline(1))
print(dok_tekst.readline(7))
dok_tekst.close()
print()
print("Odczytywanie po jednym wierszu na raz.")
dok_tekst = open("odczytaj_to.txt", "r")
print(dok_tekst.readline())
print(dok_tekst.readline())
print(dok_tekst.readline())
dok_tekst.close()
print()
print("Wczytanie całego pliku do listy.")
dok_tekst = open("odczytaj_to.txt", "r")
print(dok_tekst.readlines())
dok_tekst.close()
print()
print("Wczytanie całego pliku z listy.")
dok_tekst = open("odczytaj_to.txt", "r")
linie = dok_tekst.readlines()
print(linie)
print(len(linie))
for linia in linie:
    print(linia)
dok_tekst.close()
print()
print("Pobieranie zawartości pliku po wierszu przy użyciu pętli.")
dok_tekst = open("odczytaj_to.txt", "r")
for linia in dok_tekst:
    print(linia)
dok_tekst.close()